/**
 * WHO Essential Medicines + Disease enrichment
 * Run: node scripts/add_who_medicines.js
 */
const fs = require('fs');
const path = require('path');

const DB_PATH = path.resolve(__dirname, '../src/data/medicines_db.json');
const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));
const existing = new Set(db.medicines.map(m => m.name.toLowerCase()));

const whoMeds = [
  { name: 'Morphine', composition: 'Morphine Sulfate', uses: 'Severe pain management, palliative care, post-surgical pain.', side_effects: 'Constipation, drowsiness, nausea, respiratory depression at high doses.', precautions: 'Highly addictive. Use only under strict medical supervision.', warnings: 'Risk of respiratory depression, especially if combined with CNS depressants.', treating: ['Severe Pain', 'Palliative Care'], interactions: [{ medicine: 'Alcohol', severity: 'high', description: 'May cause fatal respiratory depression.' }] },
  { name: 'Insulin Glargine', composition: 'Long-acting Insulin Analog', uses: 'Type 1 and Type 2 Diabetes — once-daily basal insulin.', side_effects: 'Hypoglycemia, injection site reactions, weight gain.', precautions: 'Monitor blood glucose regularly. Never mix with other insulins.', warnings: 'Risk of hypoglycemia if meal is skipped.', treating: ['Type 1 Diabetes', 'Type 2 Diabetes'], interactions: [] },
  { name: 'Insulin Regular', composition: 'Short-acting Human Insulin', uses: 'Type 1 and Type 2 Diabetes — mealtime blood sugar control.', side_effects: 'Hypoglycemia, weight gain, injection site redness.', precautions: 'Inject 30 minutes before meals.', warnings: 'Incorrect dose can be fatal. Check expiry date.', treating: ['Diabetes'], interactions: [] },
  { name: 'Warfarin', composition: 'Warfarin Sodium', uses: 'Prevention of blood clots, DVT, pulmonary embolism, and stroke in atrial fibrillation.', side_effects: 'Bleeding (major risk), bruising, hair loss.', precautions: 'Regular INR blood tests essential. Consistent diet regarding Vitamin K.', warnings: 'Interaction with many foods and drugs. Life-threatening bleeding risk.', treating: ['Blood Clots', 'DVT', 'Atrial Fibrillation'], interactions: [{ medicine: 'Aspirin', severity: 'high', description: 'Significantly increases bleeding risk.' }] },
  { name: 'Atenolol', composition: 'Atenolol (Beta-blocker)', uses: 'Hypertension, angina, and heart rate control after myocardial infarction.', side_effects: 'Fatigue, cold extremities, dizziness, slow heart rate.', precautions: 'Do not stop abruptly. Monitor heart rate.', warnings: 'Can worsen asthma and COPD. Not safe for severe heart block.', treating: ['Hypertension', 'Angina', 'Heart Rate Control'], interactions: [] },
  { name: 'Propranolol', composition: 'Propranolol Hydrochloride', uses: 'Hypertension, anxiety, migraine prevention, heart rhythm disorders.', side_effects: 'Fatigue, cold hands/feet, nightmares, depression.', precautions: 'Do not stop suddenly. Avoid in asthma patients.', warnings: 'Can mask hypoglycemia symptoms in diabetics.', treating: ['Hypertension', 'Anxiety', 'Migraine Prevention'], interactions: [] },
  { name: 'Furosemide', composition: 'Furosemide (Loop Diuretic)', uses: 'Heart failure, edema (swelling), high blood pressure, kidney disorders.', side_effects: 'Frequent urination, electrolyte imbalance, dizziness, dehydration.', precautions: 'Monitor potassium levels. Take in morning to avoid nighttime urination.', warnings: 'Can cause profound electrolyte loss if overused.', treating: ['Heart Failure', 'Edema', 'Hypertension'], interactions: [] },
  { name: 'Spironolactone', composition: 'Spironolactone (Potassium-sparing diuretic)', uses: 'Heart failure, hypertension, fluid retention, PCOS, acne.', side_effects: 'Breast tenderness, high potassium, dizziness.', precautions: 'Monitor potassium levels. Avoid potassium supplements.', warnings: 'Risk of hyperkalemia which can cause dangerous heart rhythm.', treating: ['Heart Failure', 'PCOS', 'Acne', 'Hypertension'], interactions: [] },
  { name: 'Digoxin', composition: 'Digoxin (Cardiac Glycoside)', uses: 'Atrial fibrillation and heart failure — slows and strengthens heartbeat.', side_effects: 'Nausea, vision changes (yellow halos), irregular heartbeat.', precautions: 'Very narrow therapeutic window. Regular blood tests required.', warnings: 'Toxicity is serious — symptoms include vision changes and confusion.', treating: ['Atrial Fibrillation', 'Heart Failure'], interactions: [{ medicine: 'Amiodarone', severity: 'high', description: 'Increases digoxin levels causing toxicity.' }] },
  { name: 'Prednisolone', composition: 'Prednisolone (Corticosteroid)', uses: 'Asthma, rheumatoid arthritis, allergic conditions, inflammatory bowel disease.', side_effects: 'Weight gain, insomnia, increased infection risk, high blood sugar, bone thinning.', precautions: 'Do not stop abruptly if taken long-term. Take with food.', warnings: 'Long-term use causes adrenal suppression and osteoporosis.', treating: ['Asthma', 'Arthritis', 'Allergy', 'Inflammation'], interactions: [] },
  { name: 'Dexamethasone', composition: 'Dexamethasone (Corticosteroid)', uses: 'Severe inflammation, allergic reactions, COVID-19 severe disease, brain swelling, cancer-related inflammation.', side_effects: 'Hyperglycemia, fluid retention, immunosuppression, mood changes.', precautions: 'Monitor blood sugar closely. Taper slowly.', warnings: 'Can mask signs of infection. Do not use in systemic fungal infections.', treating: ['Inflammation', 'Allergic Reaction', 'Brain Swelling', 'COVID-19'], interactions: [] },
  { name: 'Ciprofloxacin', composition: 'Ciprofloxacin (Fluoroquinolone antibiotic)', uses: 'Urinary tract infections, typhoid, respiratory infections, bone infections.', side_effects: 'Tendon damage, nausea, diarrhea, sun sensitivity.', precautions: 'Avoid dairy and antacids within 2 hours. Sun protection recommended.', warnings: 'Risk of tendon rupture, especially Achilles tendon.', treating: ['UTI', 'Typhoid', 'Respiratory Infection'], interactions: [{ medicine: 'Warfarin', severity: 'moderate', description: 'Increases anticoagulant effect.' }] },
  { name: 'Cotrimoxazole', composition: 'Trimethoprim + Sulfamethoxazole', uses: 'Urinary tract infections, Pneumocystis pneumonia in HIV, toxoplasmosis.', side_effects: 'Rash (can be serious), nausea, kidney damage.', precautions: 'Adequate hydration required. Monitor kidney function.', warnings: 'Can cause severe skin reactions (Steven-Johnson syndrome).', treating: ['UTI', 'HIV Prophylaxis', 'Bacterial Infection'], interactions: [] },
  { name: 'Hydroxychloroquine', composition: 'Hydroxychloroquine Sulfate', uses: 'Rheumatoid arthritis, lupus, malaria prevention and treatment.', side_effects: 'Eye damage (retinopathy) with long-term use, nausea, dizziness.', precautions: 'Regular eye check-ups every 6 months.', warnings: 'Can cause serious cardiac arrhythmias at high doses.', treating: ['Rheumatoid Arthritis', 'Lupus', 'Malaria'], interactions: [] },
  { name: 'Salbutamol', composition: 'Albuterol / Salbutamol (Short-acting Beta-agonist)', uses: 'Immediate relief (rescue inhaler) for asthma and COPD bronchospasm.', side_effects: 'Tremors, palpitations, headache.', precautions: 'Use as rescue inhaler only. Overuse indicates poor control.', warnings: 'If you need more than 2 puffs > 2 days/week, see doctor.', treating: ['Asthma', 'COPD', 'Bronchospasm'], interactions: [] },
  { name: 'Montelukast', composition: 'Leukotriene Receptor Antagonist', uses: 'Asthma prevention, seasonal allergies, exercise-induced bronchospasm.', side_effects: 'Headache, abdominal pain, rare neuropsychiatric effects (mood changes).', precautions: 'Not for acute asthma attacks. Take in evening.', warnings: 'FDA warning about serious mental health side effects.', treating: ['Asthma', 'Allergy', 'Hay Fever'], interactions: [] },
  { name: 'Rabeprazole', composition: 'Rabeprazole Sodium (Proton Pump Inhibitor)', uses: 'GERD, stomach ulcers, H. pylori eradication (with antibiotics).', side_effects: 'Headache, diarrhea, nausea.', precautions: 'Take 30 minutes before food. Check for H. pylori if ulcers persist.', warnings: 'Long-term use may reduce magnesium and B12 levels.', treating: ['GERD', 'Ulcer', 'Acidity'], interactions: [] },
  { name: 'Domperidone', composition: 'Domperidone (Antiemetic)', uses: 'Nausea, vomiting, gastroparesis (slow stomach emptying).', side_effects: 'Dry mouth, headache, breast discharge (rare).', precautions: 'Do not use in neonates or patients with liver problems.', warnings: 'Risk of cardiac arrhythmia at high doses or in vulnerable patients.', treating: ['Nausea', 'Vomiting', 'Gastroparesis'], interactions: [] },
  { name: 'Ondansetron', composition: 'Ondansetron Hydrochloride (5-HT3 antagonist)', uses: 'Prevention of chemotherapy-induced nausea and vomiting, post-operative nausea.', side_effects: 'Headache, constipation, dizziness.', precautions: 'Monitor ECG in patients at risk of QT prolongation.', warnings: 'Avoid large doses as it can cause serotonin syndrome.', treating: ['Nausea', 'Chemotherapy-Induced Vomiting'], interactions: [] },
  { name: 'Clonazepam', composition: 'Clonazepam (Benzodiazepine)', uses: 'Epilepsy, panic disorder, anxiety, akathisia.', side_effects: 'Sedation, dizziness, memory impairment, dependence.', precautions: 'Never stop suddenly after long-term use. Habit-forming.', warnings: 'Respiratory depression risk when combined with opioids or alcohol.', treating: ['Epilepsy', 'Anxiety', 'Panic Disorder'], interactions: [{ medicine: 'Alcohol', severity: 'high', description: 'Dangerous increase in sedation, risk of respiratory arrest.' }] },
  { name: 'Alprazolam', composition: 'Alprazolam (Benzodiazepine)', uses: 'Anxiety disorders and panic disorder — short-term use only.', side_effects: 'Sedation, confusion, memory problems, dependence.', precautions: 'Do not drive. Avoid alcohol. Short-term use only.', warnings: 'High addiction potential. Cannot be stopped abruptly.', treating: ['Anxiety', 'Panic Disorder'], interactions: [] },
  { name: 'Escitalopram', composition: 'Escitalopram Oxalate (SSRI)', uses: 'Depression, generalized anxiety disorder, social anxiety, OCD.', side_effects: 'Nausea, insomnia, sexual dysfunction, increased sweating.', precautions: 'Takes 2-4 weeks for full effect. Do not stop abruptly.', warnings: 'May increase suicidal thoughts in young adults initially.', treating: ['Depression', 'Anxiety', 'OCD'], interactions: [] },
  { name: 'Amitriptyline', composition: 'Amitriptyline Hydrochloride (Tricyclic Antidepressant)', uses: 'Depression, neuropathic pain, migraine prevention, insomnia.', side_effects: 'Dry mouth, drowsiness, constipation, weight gain, heart rhythm changes.', precautions: 'Take at bedtime. Avoid in elderly due to fall risk.', warnings: 'Overdose can be fatal. Cardiac toxicity risk.', treating: ['Depression', 'Neuropathic Pain', 'Migraine'], interactions: [] },
  { name: 'Phenytoin', composition: 'Phenytoin Sodium (Anticonvulsant)', uses: 'Epilepsy — tonic-clonic and partial seizures.', side_effects: 'Gum overgrowth, acne, facial hair, ataxia, confusion.', precautions: 'Regular drug level monitoring required.', warnings: 'Zero-order kinetics: small dose increases can cause toxicity.', treating: ['Epilepsy', 'Seizures'], interactions: [] },
  { name: 'Tenofovir', composition: 'Tenofovir Disoproxil Fumarate (NRTI antiretroviral)', uses: 'HIV infection treatment (as part of combination therapy). Hepatitis B.', side_effects: 'Kidney toxicity, bone density loss, nausea.', precautions: 'Monitor kidney function and bone density. Take with food.', warnings: 'Severe lactic acidosis if stopped abruptly in Hepatitis B patients.', treating: ['HIV', 'Hepatitis B'], interactions: [] },
  { name: 'Rifampicin', composition: 'Rifampicin (Rifampin) antibiotic', uses: 'Tuberculosis (TB) treatment, leprosy, meningococcal prophylaxis.', side_effects: 'Orange-red urine/sweat/tears, liver toxicity, nausea.', precautions: 'Do not skip doses. Warn patients about red body fluids.', warnings: 'Major drug-drug interactions — reduces effectiveness of many medicines including oral contraceptives.', treating: ['Tuberculosis', 'Leprosy', 'Meningitis Prophylaxis'], interactions: [] },
  { name: 'Isoniazid', composition: 'Isoniazid (INH) antibiotic', uses: 'Tuberculosis treatment and prevention (TB prophylaxis).', side_effects: 'Peripheral neuropathy (tingling in hands/feet), liver toxicity, rash.', precautions: 'Take with Vitamin B6 (Pyridoxine) to prevent neuropathy.', warnings: 'Liver function tests needed regularly. Alcohol worsens liver toxicity.', treating: ['Tuberculosis'], interactions: [] },
  { name: 'Carbamazepine', composition: 'Carbamazepine (Anticonvulsant)', uses: 'Epilepsy, trigeminal neuralgia, bipolar disorder.', side_effects: 'Dizziness, rash, low sodium, liver effects.', precautions: 'Regular blood counts and liver function tests needed.', warnings: 'Severe skin reactions (Steven-Johnson syndrome) possible, especially in Asian populations — HLA-B*1502 testing recommended.', treating: ['Epilepsy', 'Neuralgia', 'Bipolar Disorder'], interactions: [] },
  { name: 'Levetiracetam', composition: 'Levetiracetam (Anticonvulsant)', uses: 'Epilepsy — adjunctive therapy for partial, myoclonic, and tonic-clonic seizures.', side_effects: 'Mood changes, behavioral problems, drowsiness, headache.', precautions: 'Monitor mood and behavior. Do not stop abruptly.', warnings: 'Rare psychiatric side effects including suicidal ideation.', treating: ['Epilepsy', 'Seizures'], interactions: [] },
];

let added = 0;
for (const med of whoMeds) {
  if (!existing.has(med.name.toLowerCase())) {
    db.medicines.push({ ...med, interactions: med.interactions || [] });
    existing.add(med.name.toLowerCase());
    added++;
  }
}

// Enrich diseases
const newDiseases = [
  { name: 'Depression', explanation: 'A mental disorder characterized by persistent low mood, loss of interest, and impaired daily functioning.', biology: 'Disruption in serotonin, dopamine, and norepinephrine neurotransmitter systems in the prefrontal cortex and limbic system.', common_meds: ['Escitalopram', 'Fluoxetine', 'Sertraline Hydrochloride', 'Amitriptyline'] },
  { name: 'Anxiety', explanation: 'Excessive, uncontrollable worry that interferes with daily activities.', biology: 'Overactivation of the amygdala (fear center) and HPA stress axis, with dysregulation of GABA and serotonin.', common_meds: ['Escitalopram', 'Clonazepam', 'Alprazolam', 'Propranolol'] },
  { name: 'Tuberculosis (TB)', explanation: 'A serious bacterial infection caused by Mycobacterium tuberculosis, primarily affecting the lungs.', biology: 'Mycobacterium tuberculosis infects macrophages and forms granulomas. It can remain latent for years.', common_meds: ['Rifampicin', 'Isoniazid', 'Pyrazinamide', 'Ethambutol'] },
  { name: 'HIV/AIDS', explanation: 'HIV destroys CD4 T-cells, progressively weakening the immune system until AIDS develops.', biology: 'HIV is a retrovirus that integrates its genome into host T-cells, making it impossible to clear without treatment.', common_meds: ['Tenofovir', 'Efavirenz', 'Lamivudine', 'Cotrimoxazole'] },
  { name: 'Malaria', explanation: 'A life-threatening parasitic infection transmitted by Anopheles mosquitoes.', biology: 'Plasmodium parasites infect red blood cells and liver cells, causing cyclical fever, chills, and organ damage.', common_meds: ['Hydroxychloroquine', 'Artemether-Lumefantrine', 'Doxycycline', 'Primaquine'] },
  { name: 'Epilepsy', explanation: 'A neurological disorder causing recurrent unprovoked seizures due to abnormal brain electrical activity.', biology: 'Imbalance between excitatory (glutamate) and inhibitory (GABA) neurotransmission in the brain.', common_meds: ['Phenytoin', 'Clonazepam', 'Valproic Acid', 'Levetiracetam', 'Carbamazepine'] },
  { name: 'Heart Failure', explanation: 'The heart cannot pump enough blood to meet the body needs.', biology: 'Caused by damaged or weakened cardiac muscle (myocardium), leading to ventricular remodeling and neurohumoral activation.', common_meds: ['Furosemide', 'Spironolactone', 'Atenolol', 'Digoxin', 'Lisinopril'] },
  { name: 'Rheumatoid Arthritis', explanation: 'An autoimmune disease causing chronic inflammation in joints.', biology: 'Autoreactive T-cells and B-cells target synovial tissue, releasing TNF-alpha and IL-6, destroying cartilage and bone.', common_meds: ['Methotrexate', 'Hydroxychloroquine', 'Prednisolone', 'Sulfasalazine'] },
  { name: 'COPD', explanation: 'Chronic Obstructive Pulmonary Disease — progressive lung disease causing breathing difficulty.', biology: 'Smoke/pollution destroys alveoli and causes chronic bronchitis, reducing lung elasticity (emphysema).', common_meds: ['Salbutamol', 'Ipratropium', 'Tiotropium', 'Prednisolone'] },
  { name: 'UTI (Urinary Tract Infection)', explanation: 'Bacterial infection of the urinary tract including bladder and kidneys.', biology: 'Bacteria (usually E. coli) colonize the urethra and ascend to the bladder, causing inflammation.', common_meds: ['Ciprofloxacin', 'Cotrimoxazole', 'Nitrofurantoin', 'Amoxicillin'] },
  { name: 'Atrial Fibrillation', explanation: 'Irregular, often rapid heart rate that can increase risk of stroke and heart failure.', biology: 'Disorganized electrical signals in the atria cause chaotic contractions instead of coordinated pumping.', common_meds: ['Warfarin', 'Digoxin', 'Atenolol', 'Amiodarone'] },
];

const existingDiseases = new Set(db.diseases.map(d => d.name.toLowerCase()));
let addedDiseases = 0;
for (const d of newDiseases) {
  if (!existingDiseases.has(d.name.toLowerCase())) {
    db.diseases.push(d);
    existingDiseases.add(d.name.toLowerCase());
    addedDiseases++;
  }
}

fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));
console.log(`Medicines: ${db.medicines.length} (+${added} WHO Essential Medicines)`);
console.log(`Diseases: ${db.diseases.length} (+${addedDiseases} conditions)`);
console.log('Done!');
